/**
 * Public site config · safe to commit to GitHub.
 * Supabase publishable URL/key are public client values (RLS + server PIN check protect data).
 * PINs are never stored here · only in Supabase rep_pins.
 */
window.SITE_CONFIG = {
  companyName: "Dashboard",
  brandLogoUrl: "doc/Crown.png",
  ownerName: "Delexo",
  ownerHandle: "@delexo",
  ownerPhotoUrl: "https://raw.githubusercontent.com/Delexoo/Dashboard/main/doc/meettheowner.jpg",
  ownerBio: "Hi, I go by Delexo online. I'm 19, ambitious, and always up for a risk.\n\nI enrolled in Harvard CS50 and I'm now an alumnus. I also completed Google Cybersecurity, and I'm currently pursuing Cybersecurity for Business at Harvard VPAL.\n\nIf you ever need any help, reach out anytime.",
  ownerBioLead: "Hi, I go by Delexo online. I'm 19, I'm majoring in Cybersecurity and Computer Science. I spend a lot of my time creating new projects, tools, courses!",
  ownerBioCreds: ["Harvard CS50 Certificate","Google Cybersecurity Certificate","The Ultimate Dark Web, Anonymity, Privacy & Security Course","Learn Ethical Hacking From Scratch","100 Days of Code: The Complete Python Pro Bootcamp",{"label":"Cybersecurity for Business · Harvard VPAL","status":"in-progress"}],
  ownerBioClose: "If you ever need help, reach out anytime.",
  ownerStoreUrl: "https://delexo.store",
  ownerCalUrl: "https://cal.com/delexo",
  honorableMentionName: "Coming soon",
  honorableMentionBio: "Profile coming soon · same image as a placeholder until your friend’s details are added here.",
  honorableMentionPhotoUrl: "https://raw.githubusercontent.com/Delexoo/Dashboard/main/doc/Default.jpg",
  contributorsPinnedFirst: ["delexo","misha"],
  contributorsVerified: ["Misha","Delexo"],
  contributorsVerifiedBadgeUrl: "https://raw.githubusercontent.com/Delexoo/Dashboard/main/doc/Verified.png",
  contributorsDefaultRole: "Sales Representative",
  contributorsRoles: {"Misha":"Co-Owner","Delexo":"CEO"},
  ownerRepIds: ["delexo"],
  contributorsShareUrl: "https://tally.so/r/1AGlbg",
  contributorsShareLabel: "Invite",
  contributorsShareHint: "Invite someone to apply",
  contributorsShareTitle: "Remote sales opportunity",
  contributorsShareText: "Hey! I'm inviting you to join a remote sales opportunity.\n\n✅ Work from home\n✅ No experience needed\n✅ Full training provided\n💰 Earn up to $600 per sale\n\nLearn more: https://tally.so/r/1AGlbg",
  ownerTelegram: "https://t.me/delexoo",
  ownerTelegramHandle: "@delexoo",
  supportTelegram: "https://t.me/delexoo",
  ownerPhoneIcon: "https://raw.githubusercontent.com/Delexoo/Dashboard/main/doc/iMessages.jpg",
  ownerCalIcon: "https://raw.githubusercontent.com/Delexoo/Dashboard/main/doc/Cal.png",
  ownerStoreIcon: "https://raw.githubusercontent.com/Delexoo/Dashboard/main/doc/delexologo.png",
  telegramTeam: "https://t.me/c/3541685239/1",
  telegramTeamName: "Official Telegram Business Chat",
  telegramTeamDisplayName: "Website Agency",
  telegramTeamJoinLabel: "Join Official Telegram Business Chat",
  telegramTeamAvatar: "doc/Crown.png",
  telegramAppIcon: "https://raw.githubusercontent.com/Delexoo/Dashboard/main/doc/Telegram.png",
  interestedBusinessesUrl: "https://t.me/c/3541685239/8",
  payoutTelegramUrl: "https://t.me/+U9wsP-sf8GFmNWFh",
  payoutTelegramName: "Website Agency",
  leadsListUrl: "leads.html",
  supabaseUrl: "https://qxtvrlskuntfcsgqdekh.supabase.co",
  supabaseAnonKey: "sb_publishable_1aqaA4jT-naO9ELuS-B6oQ_rDAg6YR-",
  useSupabaseLeads: true,
  useRepSettingsSync: true,
  useBugReports: true,
  useFeedback: true,
  useNewClients: true,
  useFaqQa: true,
  onboardingVideoUrl: "https://youtu.be/BPbOQqbex98?si=wBPx0bqtRxfaQJrf",
  courseModuleVideos: {"introduction":"https://youtu.be/mXOzM9eNC_A","setup-accounts":"https://youtu.be/tgdvS4wTPrA","preferences":""},
  onboardingVideoLabel: "Legacy fallback video (until per-module clips are set)",
  email: "fullprofessionalwebsites@outlook.com",
  phone: "(401) 300-0957",
  packages: [
    { upfront: "$500", monthly: "$5/mo", commission: "$200" },
    { upfront: "$700", monthly: "$20/mo", commission: "$280" },
    { upfront: "$1,000", monthly: "$10/mo", commission: "$400" },
    { upfront: "$1,500", monthly: "$10/mo", commission: "$600" }
  ],
  reps: []
};
